### ISSUE TITLE
Do not use async in errorbacks

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-proxy#13]
In https://github.com/fastify/fast-proxy/blob/238019d4b556f8de2797c12da1751a3e34bf9bc3/index.js#L78 an `async` function is used in an errorback. Doing so exposes us at a risk of memory leaks and DoS attacks in case an unplanned error (bug) occurs that would be extremely hard to track.

**Comment by jkyberneees** [comment]
Good catch, actually for no reason as I can see. Will fix accordingly...

**Comment by trygve-lie** [comment]
Solved by #16
