### ISSUE TITLE
Enabling different base per request

### ISSUE THREAD

**Issue by yohay-ma** [fastify/fast-proxy#22]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal
Enable changing the base on each request will enable dynamic routing without the need to preconfigure proxies for different  targets

## Example
```proxy(req, res, req.url, {base: route})```

## code change:
https://github.com/fastify/fast-proxy/blob/d9717ce2194f2c2dc4eb91d7e5c7c66f11ab4b2d/index.js#L47

change:
```        url = new URL(source, base)```
to
```        url = new URL(source, opts.base)```

**Comment by jkyberneees** [comment]
Hi @yohay-ma thanks for taking your time to contribute to this library improvements. 
I do find your suggestion appropriated. I will properly push a MR for this. 

Thanks.
