### ISSUE TITLE
add an optional flag not to use caching

### ISSUE THREAD

**Issue by yohayg** [fastify/fast-proxy#25]
## 🚀 Feature Proposal

add an optional flag not to use caching

## Motivation

In my application 99% of the url are dynamically routes. i.e. /users/:userId/orders/:orderId and also use query params

therefore the cache is not required. 

## Example
`    const { proxy, close } = fastProxy({
      base: null,
      useCache: false
    });`

Thanks,

Yohay

**Comment by jkyberneees** [comment]
Hi @yohayg, it does makes sense to have this caching strategy configurable. 
I will push the feature ASAP.

Regards
