### ISSUE TITLE
Server crash when aborting wrk when using fast-proxy with 0http with low server

### ISSUE THREAD

**Issue by yohayg** [fastify/fast-proxy#35]
## 🐛 Bug Report

Server crash when aborting `wrk` when using `fast-proxy` with `0http` with `low` server

## To Reproduce

I have the following code:
(Happens also without undici)
```js
    const { proxy } = fastProxy({
      base: 'http://localhost:4000',
      undiciOptions: {
        connections: 4000,
        pipelining: 20,
        requestTimeout: 5000,
      },
    });
    const { router, server } = cero({
      server: low(),
    });

    router.all('/*', (req, res) => proxy(req, res, req.url, {}));

    server.listen(3000, (socket) => {
      if (socket) {
        console.log('HTTP server ready!');
      }
    });
```
With an additional `restana` server listening on port 4000
Then run 
`wrk -t8 -c50 -d20s http://localhost:3000/api/v1/test`
hit CTRL-C to stop `wrk`.

Result:
process abort on with the following error:

```
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
There was an uncaught exception. I'm now going to commit suicide; farewell all.
```

When I'm using `0http` **without** `low` it doesn’t  happen
## Expected behavior

The process should not abort if I stop `wrk` 
## Your Environment

- *node version*: 12
- *fast-prxy version*: latest
- *os*: Mac

**Comment by jkyberneees** [comment]
Hi @yohayg thanks for reporting this issue. 

However, this is not related to `fast-proxy`, I would suggest you to move this issue to the `0http` project. 
> Unfortunately I am not planning to further support `uWebSocket.js` on `low` implementation. We can keep the conversation in there...

Best Regards

**Comment by yohay-ma** [comment]
ok. I'm fine with closing this issue. thanks

**Comment by jkyberneees** [comment]
Just opened the issue in https://github.com/jkyberneees/0http/issues/16
Thanks
