### ISSUE TITLE
Getting 500 `invalid connection header` using fast-proxy with undici

### ISSUE THREAD

**Issue by batusai513** [fastify/fast-proxy#49]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### fast-proxy version

2.0.0

### Node.js version

12.20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15

### Description

When I try to use fast-proxy with undici as client on a next.js API route to proxy browser requests i get an 500 error `invalid connection header`

### Steps to Reproduce

- create next.js app
- create `pages/v1/[...args].js` (route to proxy)
- add the proxy code 
```js
import { NextApiRequest, NextApiResponse } from 'next';
const { proxy } = require('fast-proxy')({
  base: process.env.EXTERNAL_API_URL,
  undici: {
     connections: 100,
     pipelining: 0,
   },
});

export default function api(req: NextApiRequest, res: NextApiResponse) {
  return runMiddleware(req, res, () => proxy(req, res, req.url, {}));
}

export const config = {
  api: {
    bodyParser: false,
  },
};

//@ts-expect-error
function runMiddleware(req, res, fn) {
  return new Promise((resolve, reject) => {
    //@ts-expect-error
    fn(req, res, (result) => {
      if (result instanceof Error) {
        return reject(result);
      }

      return resolve(result);
    });
  });
}
```
- when performing a request, it get's captured and passed to the proxy, the proxy returns 500, this doesn't happen if I remove the undici options.

### Expected Behavior

When I perform a proxy request with undici activated, it should not return 500

**Comment by eljefedelrodeodeljefe** [comment]
You likely made an HTTP request via Postman. They add a connection header automatically. Undici however does not support that. Their reason is not clear to me, however I believe this makes it spec or performance compliant. https://github.com/nodejs/undici/blame/cd78eb57203ce85a26312290c1bef4017e30cf74/lib/core/request.js#L205

A hot fix is:

```js
    delete req.raw.headers.connection

    proxyInstance.proxy(req.raw, reply.raw, uri, {})
```

My learning from that issue is, that I likely will not use undici for user facing apis, as I cannot guarantee header sanity.

**Comment by batusai513** [comment]
@eljefedelrodeodeljefe Thanks for your answer, that last example help with the issue 🙇🏼‍♂️
