### ISSUE TITLE
Is there an interface to use proxy in koa.js?

### ISSUE THREAD

**Issue by budarin** [fastify/fast-proxy#53]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We would like to use fast-proxy in our koa application.
Is there a proxy call option that is compatible with kos?

**Comment by sveisvei** [comment]
I am using it in non-fastify with no-problem: You need to pass the raw node request and response, e.g. 

```
fastProxyInstance.proxy(request, response, path, {  });
```

**Comment by budarin** [comment]
@sveisvei  thanks, I will try!

**Comment by Fdawgs** [comment]
> @sveisvei  thanks, I will try!

Did @sveisvei's suggestion resolve your issue?
