### ISSUE TITLE
Undici crashes server

### ISSUE THREAD

**Issue by sveisvei** [fastify/fast-proxy#55]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

?

### Node.js version

14.17.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

Proxy crashes server when proxying multiple similar requests.

```
 err: {
      "type": "TypeError",
      "message": "Cannot read property 'upgrade' of undefined",
      "stack":
          TypeError: Cannot read property 'upgrade' of undefined
              at Parser.2 (/undici@3.3.6/node_modules/undici/lib/core/client.js:546:17)
    }
```

There is a bug fixed in undici, which seem fixed in later versions. https://github.com/nodejs/undici/issues/756

Confirmed on my machine that the error does not occur on `undici=4.9.5`

### Steps to Reproduce

https://github.com/nodejs/undici/issues/756 has a comment on how to reproduce: 

https://github.com/nodejs/undici/issues/756#issuecomment-890371578

**Comment by sveisvei** [comment]
@jkyberneees Can you create a new release with latest undici?

**Comment by sveisvei** [comment]
Is this repository abandoned? I can create PR if wanted.

**Comment by jkyberneees** [comment]
Hi @sveisvei, thanks for being proactive regarding this issue. Please go ahead and open a PR, you are welcome.

Regards
