### ISSUE TITLE
Archiving this module / Do not use / New maintainer needed

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-proxy#91]
I think we should be archiving this module, because it was born out of the will of @jkyberneees and myself to merge it and fastify-reply-from, creating a generic module for proxying in node.js.
However, such goals never materialized.

I would like to transfer this module back to @jkyberneees or archive this module if he is not interested in maintaining it anymore.

---

For some strange reasons I cannot add other people to do releases on this module, and I have no time to do them.

**Comment by jsumners** [comment]
+1

**Comment by Uzlopak** [comment]
I prefer archiving over transferring out of the fastify org.

**Comment by q0rban** [comment]
This is a bummer, as we recently refactored our app to use this module after doing some benchmarks of this and other nodejs proxying modules.

**Comment by jsumners** [comment]
A willing maintainer is also an option.

**Comment by gurgunday** [comment]
Seems like no one is willing either, should we go ahead and archive the repo?

**Comment by q0rban** [comment]
FWIW, we ended up refactoring to fastify/http-proxy after hearing of plans to abandon this project.

**Comment by mcollina** [comment]
The module is deprecated on npm.
